// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Identifier struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ClientId             int32    `protobuf:"varint,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (m *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(m, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Identifier) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

type Point struct {
	Version              uint32   `protobuf:"fixed32,1,opt,name=version,proto3" json:"version,omitempty"`
	MessageType          string   `protobuf:"bytes,2,opt,name=messageType,proto3" json:"messageType,omitempty"`
	NetType              string   `protobuf:"bytes,3,opt,name=netType,proto3" json:"netType,omitempty"`
	DeviceId             uint32   `protobuf:"fixed32,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	BatteryPercent       uint32   `protobuf:"fixed32,5,opt,name=batteryPercent,proto3" json:"batteryPercent,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,6,opt,name=receiveTime,proto3" json:"receiveTime,omitempty"`
	DeviceTime           int64    `protobuf:"varint,7,opt,name=deviceTime,proto3" json:"deviceTime,omitempty"`
	Latitude             float64  `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Point) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *Point) GetNetType() string {
	if m != nil {
		return m.NetType
	}
	return ""
}

func (m *Point) GetDeviceId() uint32 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *Point) GetBatteryPercent() uint32 {
	if m != nil {
		return m.BatteryPercent
	}
	return 0
}

func (m *Point) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

func (m *Point) GetDeviceTime() int64 {
	if m != nil {
		return m.DeviceTime
	}
	return 0
}

func (m *Point) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type CacheCommand struct {
	Version              uint32   `protobuf:"fixed32,1,opt,name=version,proto3" json:"version,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheCommand) Reset()         { *m = CacheCommand{} }
func (m *CacheCommand) String() string { return proto.CompactTextString(m) }
func (*CacheCommand) ProtoMessage()    {}
func (*CacheCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{2}
}

func (m *CacheCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheCommand.Unmarshal(m, b)
}
func (m *CacheCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheCommand.Marshal(b, m, deterministic)
}
func (m *CacheCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheCommand.Merge(m, src)
}
func (m *CacheCommand) XXX_Size() int {
	return xxx_messageInfo_CacheCommand.Size(m)
}
func (m *CacheCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CacheCommand proto.InternalMessageInfo

func (m *CacheCommand) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CacheCommand) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type CacheResponse struct {
	Version              uint32   `protobuf:"fixed32,1,opt,name=version,proto3" json:"version,omitempty"`
	CacheSize            int64    `protobuf:"varint,2,opt,name=cacheSize,proto3" json:"cacheSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheResponse) Reset()         { *m = CacheResponse{} }
func (m *CacheResponse) String() string { return proto.CompactTextString(m) }
func (*CacheResponse) ProtoMessage()    {}
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{3}
}

func (m *CacheResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheResponse.Unmarshal(m, b)
}
func (m *CacheResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheResponse.Marshal(b, m, deterministic)
}
func (m *CacheResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheResponse.Merge(m, src)
}
func (m *CacheResponse) XXX_Size() int {
	return xxx_messageInfo_CacheResponse.Size(m)
}
func (m *CacheResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CacheResponse proto.InternalMessageInfo

func (m *CacheResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CacheResponse) GetCacheSize() int64 {
	if m != nil {
		return m.CacheSize
	}
	return 0
}

type ServerCommand struct {
	Version              uint32   `protobuf:"fixed32,1,opt,name=version,proto3" json:"version,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerCommand) Reset()         { *m = ServerCommand{} }
func (m *ServerCommand) String() string { return proto.CompactTextString(m) }
func (*ServerCommand) ProtoMessage()    {}
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{4}
}

func (m *ServerCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCommand.Unmarshal(m, b)
}
func (m *ServerCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCommand.Marshal(b, m, deterministic)
}
func (m *ServerCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCommand.Merge(m, src)
}
func (m *ServerCommand) XXX_Size() int {
	return xxx_messageInfo_ServerCommand.Size(m)
}
func (m *ServerCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCommand proto.InternalMessageInfo

func (m *ServerCommand) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ServerCommand) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type ServerResponse struct {
	Version              uint32                      `protobuf:"fixed32,1,opt,name=version,proto3" json:"version,omitempty"`
	ServerStatistics     []*ServerResponse_Statistic `protobuf:"bytes,4,rep,name=ServerStatistics,proto3" json:"ServerStatistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{5}
}

func (m *ServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse.Unmarshal(m, b)
}
func (m *ServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse.Marshal(b, m, deterministic)
}
func (m *ServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse.Merge(m, src)
}
func (m *ServerResponse) XXX_Size() int {
	return xxx_messageInfo_ServerResponse.Size(m)
}
func (m *ServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse proto.InternalMessageInfo

func (m *ServerResponse) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ServerResponse) GetServerStatistics() []*ServerResponse_Statistic {
	if m != nil {
		return m.ServerStatistics
	}
	return nil
}

type ServerResponse_Statistic struct {
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerResponse_Statistic) Reset()         { *m = ServerResponse_Statistic{} }
func (m *ServerResponse_Statistic) String() string { return proto.CompactTextString(m) }
func (*ServerResponse_Statistic) ProtoMessage()    {}
func (*ServerResponse_Statistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{5, 0}
}

func (m *ServerResponse_Statistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse_Statistic.Unmarshal(m, b)
}
func (m *ServerResponse_Statistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse_Statistic.Marshal(b, m, deterministic)
}
func (m *ServerResponse_Statistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse_Statistic.Merge(m, src)
}
func (m *ServerResponse_Statistic) XXX_Size() int {
	return xxx_messageInfo_ServerResponse_Statistic.Size(m)
}
func (m *ServerResponse_Statistic) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse_Statistic.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse_Statistic proto.InternalMessageInfo

func (m *ServerResponse_Statistic) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServerResponse_Statistic) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PingCommand struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingCommand) Reset()         { *m = PingCommand{} }
func (m *PingCommand) String() string { return proto.CompactTextString(m) }
func (*PingCommand) ProtoMessage()    {}
func (*PingCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{6}
}

func (m *PingCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingCommand.Unmarshal(m, b)
}
func (m *PingCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingCommand.Marshal(b, m, deterministic)
}
func (m *PingCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingCommand.Merge(m, src)
}
func (m *PingCommand) XXX_Size() int {
	return xxx_messageInfo_PingCommand.Size(m)
}
func (m *PingCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_PingCommand.DiscardUnknown(m)
}

var xxx_messageInfo_PingCommand proto.InternalMessageInfo

func (m *PingCommand) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Identifier)(nil), "proto.Identifier")
	proto.RegisterType((*Point)(nil), "proto.Point")
	proto.RegisterType((*CacheCommand)(nil), "proto.CacheCommand")
	proto.RegisterType((*CacheResponse)(nil), "proto.CacheResponse")
	proto.RegisterType((*ServerCommand)(nil), "proto.ServerCommand")
	proto.RegisterType((*ServerResponse)(nil), "proto.ServerResponse")
	proto.RegisterType((*ServerResponse_Statistic)(nil), "proto.ServerResponse.Statistic")
	proto.RegisterType((*PingCommand)(nil), "proto.PingCommand")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x9b, 0xb8, 0xa9, 0x27, 0x6d, 0x81, 0x6d, 0x90, 0x56, 0x56, 0x05, 0xd6, 0x1e, 0x20,
	0xa7, 0x80, 0x8a, 0x90, 0x38, 0xa2, 0xe6, 0x80, 0x22, 0x38, 0x44, 0x4e, 0x5f, 0xc0, 0xb5, 0x87,
	0xb0, 0x52, 0xbc, 0x8e, 0xd6, 0x1b, 0x4b, 0xe5, 0x5d, 0x78, 0x05, 0x1e, 0x8c, 0xa7, 0x40, 0x9e,
	0xf5, 0xda, 0x6e, 0xa8, 0x2a, 0xa4, 0x9e, 0xec, 0xef, 0x9b, 0x6f, 0xbe, 0xf9, 0xf1, 0x18, 0x2e,
	0x76, 0xba, 0x30, 0xc5, 0xbb, 0x1c, 0xcb, 0x32, 0xd9, 0xe0, 0x9c, 0x10, 0xf3, 0xe9, 0x21, 0xae,
	0x01, 0x96, 0x19, 0x2a, 0x23, 0xbf, 0x4b, 0xd4, 0x8c, 0xc3, 0xb8, 0x42, 0x5d, 0xca, 0x42, 0x71,
	0x2f, 0xf2, 0x66, 0x7e, 0xec, 0x20, 0x0b, 0xe1, 0x24, 0xdd, 0x4a, 0x54, 0x66, 0x99, 0xf1, 0x23,
	0x0a, 0xb5, 0x58, 0xfc, 0x3a, 0x02, 0x7f, 0x55, 0x48, 0x65, 0x0e, 0xf3, 0xc7, 0x5d, 0x7e, 0x04,
	0x93, 0xa6, 0xfe, 0xcd, 0xdd, 0x0e, 0xc9, 0x22, 0x88, 0xfb, 0x54, 0x9d, 0xab, 0xd0, 0x50, 0x74,
	0x48, 0x51, 0x07, 0xeb, 0xda, 0x19, 0x56, 0x32, 0xc5, 0x65, 0xc6, 0x47, 0x64, 0xdb, 0x62, 0xf6,
	0x06, 0xce, 0x6f, 0x13, 0x63, 0x50, 0xdf, 0xad, 0x50, 0xa7, 0xa8, 0x0c, 0xf7, 0x49, 0x71, 0xc0,
	0xd6, 0xf5, 0x35, 0xa6, 0x28, 0x2b, 0xbc, 0x91, 0x39, 0xf2, 0xe3, 0xc8, 0x9b, 0x0d, 0xe3, 0x3e,
	0xc5, 0x5e, 0x01, 0x58, 0x57, 0x12, 0x8c, 0x49, 0xd0, 0x63, 0xea, 0x2e, 0xb6, 0x89, 0x91, 0x66,
	0x9f, 0x21, 0x3f, 0x89, 0xbc, 0x99, 0x17, 0xb7, 0x98, 0x5d, 0x42, 0xb0, 0x2d, 0xd4, 0xc6, 0x06,
	0x03, 0x0a, 0x76, 0x84, 0xb8, 0x86, 0xd3, 0x45, 0x92, 0xfe, 0xc0, 0x45, 0x91, 0xe7, 0x89, 0xca,
	0x1e, 0xd9, 0x12, 0x87, 0x71, 0x6a, 0x45, 0xcd, 0x86, 0x1c, 0x14, 0x5f, 0xe0, 0x8c, 0x3c, 0x62,
	0x2c, 0x77, 0x85, 0x2a, 0xf1, 0x11, 0x93, 0x4b, 0x08, 0xd2, 0x5a, 0xba, 0x96, 0x3f, 0xed, 0xa2,
	0x87, 0x71, 0x47, 0x88, 0x05, 0x9c, 0xad, 0x51, 0x57, 0xa8, 0x9f, 0xd2, 0xcd, 0x6f, 0x0f, 0xce,
	0xad, 0xcb, 0x7f, 0xf4, 0xf3, 0x15, 0x9e, 0x5b, 0xed, 0xda, 0x24, 0x46, 0x96, 0x46, 0xa6, 0x25,
	0x1f, 0x45, 0xc3, 0xd9, 0xe4, 0xea, 0xb5, 0xbd, 0xc5, 0xf9, 0x7d, 0xab, 0x79, 0xab, 0x8b, 0xff,
	0x49, 0x0c, 0x3f, 0x42, 0xd0, 0x22, 0xc6, 0x60, 0x64, 0xba, 0x6b, 0xa2, 0x77, 0x36, 0x05, 0xbf,
	0x4a, 0xb6, 0x7b, 0x77, 0x44, 0x16, 0x88, 0xb7, 0x30, 0x59, 0x49, 0xb5, 0xe9, 0xcd, 0xdc, 0x9c,
	0x1e, 0x35, 0x1b, 0xc4, 0x0e, 0x5e, 0xfd, 0xf1, 0x00, 0x74, 0xb1, 0x37, 0x68, 0x0f, 0x7a, 0x0e,
	0xc1, 0xb7, 0xa4, 0x34, 0x16, 0xbc, 0x68, 0xda, 0xed, 0x7e, 0x98, 0xf0, 0xb4, 0xa1, 0x48, 0x20,
	0x06, 0xec, 0x13, 0x04, 0x0b, 0xb7, 0x6a, 0x76, 0xd1, 0x04, 0xfb, 0x1f, 0x3f, 0x9c, 0xf6, 0x49,
	0x37, 0xb2, 0x18, 0xb0, 0xcf, 0xf0, 0xec, 0x60, 0x58, 0x36, 0xbd, 0xb7, 0x1e, 0x67, 0xf0, 0xf2,
	0xc1, 0xa5, 0x89, 0x01, 0x7b, 0x0f, 0xa3, 0x7a, 0x46, 0xc6, 0x5c, 0x4f, 0xdd, 0xc0, 0xe1, 0x03,
	0x9c, 0x18, 0xdc, 0x1e, 0x13, 0xf9, 0xe1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x66, 0x62,
	0x98, 0x21, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoutePointClient is the client API for RoutePoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoutePointClient interface {
	LastPoint(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Point, error)
	CacheSize(ctx context.Context, in *CacheCommand, opts ...grpc.CallOption) (*CacheResponse, error)
	ServerStatistic(ctx context.Context, in *ServerCommand, opts ...grpc.CallOption) (*ServerResponse, error)
	Ping(ctx context.Context, in *PingCommand, opts ...grpc.CallOption) (*PingCommand, error)
}

type routePointClient struct {
	cc *grpc.ClientConn
}

func NewRoutePointClient(cc *grpc.ClientConn) RoutePointClient {
	return &routePointClient{cc}
}

func (c *routePointClient) LastPoint(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Point, error) {
	out := new(Point)
	err := c.cc.Invoke(ctx, "/proto.routePoint/LastPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routePointClient) CacheSize(ctx context.Context, in *CacheCommand, opts ...grpc.CallOption) (*CacheResponse, error) {
	out := new(CacheResponse)
	err := c.cc.Invoke(ctx, "/proto.routePoint/CacheSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routePointClient) ServerStatistic(ctx context.Context, in *ServerCommand, opts ...grpc.CallOption) (*ServerResponse, error) {
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, "/proto.routePoint/ServerStatistic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routePointClient) Ping(ctx context.Context, in *PingCommand, opts ...grpc.CallOption) (*PingCommand, error) {
	out := new(PingCommand)
	err := c.cc.Invoke(ctx, "/proto.routePoint/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutePointServer is the server API for RoutePoint service.
type RoutePointServer interface {
	LastPoint(context.Context, *Identifier) (*Point, error)
	CacheSize(context.Context, *CacheCommand) (*CacheResponse, error)
	ServerStatistic(context.Context, *ServerCommand) (*ServerResponse, error)
	Ping(context.Context, *PingCommand) (*PingCommand, error)
}

func RegisterRoutePointServer(s *grpc.Server, srv RoutePointServer) {
	s.RegisterService(&_RoutePoint_serviceDesc, srv)
}

func _RoutePoint_LastPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutePointServer).LastPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.routePoint/LastPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutePointServer).LastPoint(ctx, req.(*Identifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutePoint_CacheSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutePointServer).CacheSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.routePoint/CacheSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutePointServer).CacheSize(ctx, req.(*CacheCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutePoint_ServerStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutePointServer).ServerStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.routePoint/ServerStatistic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutePointServer).ServerStatistic(ctx, req.(*ServerCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutePoint_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutePointServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.routePoint/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutePointServer).Ping(ctx, req.(*PingCommand))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoutePoint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.routePoint",
	HandlerType: (*RoutePointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LastPoint",
			Handler:    _RoutePoint_LastPoint_Handler,
		},
		{
			MethodName: "CacheSize",
			Handler:    _RoutePoint_CacheSize_Handler,
		},
		{
			MethodName: "ServerStatistic",
			Handler:    _RoutePoint_ServerStatistic_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _RoutePoint_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/message.proto",
}
