// Code generated by protoc-gen-go. DO NOT EDIT.
// source: point_service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Identifier struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc56ba28a6aaff3d, []int{0}
}

func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (m *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(m, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Identifier) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type Point struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	MessageType          string   `protobuf:"bytes,2,opt,name=messageType,proto3" json:"messageType,omitempty"`
	NetType              string   `protobuf:"bytes,3,opt,name=netType,proto3" json:"netType,omitempty"`
	DeviceId             string   `protobuf:"bytes,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	BatteryPercent       uint32   `protobuf:"fixed32,5,opt,name=batteryPercent,proto3" json:"batteryPercent,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,6,opt,name=receiveTime,proto3" json:"receiveTime,omitempty"`
	DeviceTime           int64    `protobuf:"varint,7,opt,name=deviceTime,proto3" json:"deviceTime,omitempty"`
	Latitude             float64  `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc56ba28a6aaff3d, []int{1}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Point) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *Point) GetNetType() string {
	if m != nil {
		return m.NetType
	}
	return ""
}

func (m *Point) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Point) GetBatteryPercent() uint32 {
	if m != nil {
		return m.BatteryPercent
	}
	return 0
}

func (m *Point) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

func (m *Point) GetDeviceTime() int64 {
	if m != nil {
		return m.DeviceTime
	}
	return 0
}

func (m *Point) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type ServerCommand struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerCommand) Reset()         { *m = ServerCommand{} }
func (m *ServerCommand) String() string { return proto.CompactTextString(m) }
func (*ServerCommand) ProtoMessage()    {}
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc56ba28a6aaff3d, []int{2}
}

func (m *ServerCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCommand.Unmarshal(m, b)
}
func (m *ServerCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCommand.Marshal(b, m, deterministic)
}
func (m *ServerCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCommand.Merge(m, src)
}
func (m *ServerCommand) XXX_Size() int {
	return xxx_messageInfo_ServerCommand.Size(m)
}
func (m *ServerCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCommand proto.InternalMessageInfo

func (m *ServerCommand) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServerCommand) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type ServerResponse struct {
	Version              string                      `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ServerStatistics     []*ServerResponse_Statistic `protobuf:"bytes,4,rep,name=ServerStatistics,proto3" json:"ServerStatistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ServerResponse) Reset()         { *m = ServerResponse{} }
func (m *ServerResponse) String() string { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()    {}
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc56ba28a6aaff3d, []int{3}
}

func (m *ServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse.Unmarshal(m, b)
}
func (m *ServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse.Marshal(b, m, deterministic)
}
func (m *ServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse.Merge(m, src)
}
func (m *ServerResponse) XXX_Size() int {
	return xxx_messageInfo_ServerResponse.Size(m)
}
func (m *ServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse proto.InternalMessageInfo

func (m *ServerResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServerResponse) GetServerStatistics() []*ServerResponse_Statistic {
	if m != nil {
		return m.ServerStatistics
	}
	return nil
}

type ServerResponse_Statistic struct {
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerResponse_Statistic) Reset()         { *m = ServerResponse_Statistic{} }
func (m *ServerResponse_Statistic) String() string { return proto.CompactTextString(m) }
func (*ServerResponse_Statistic) ProtoMessage()    {}
func (*ServerResponse_Statistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc56ba28a6aaff3d, []int{3, 0}
}

func (m *ServerResponse_Statistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerResponse_Statistic.Unmarshal(m, b)
}
func (m *ServerResponse_Statistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerResponse_Statistic.Marshal(b, m, deterministic)
}
func (m *ServerResponse_Statistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerResponse_Statistic.Merge(m, src)
}
func (m *ServerResponse_Statistic) XXX_Size() int {
	return xxx_messageInfo_ServerResponse_Statistic.Size(m)
}
func (m *ServerResponse_Statistic) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerResponse_Statistic.DiscardUnknown(m)
}

var xxx_messageInfo_ServerResponse_Statistic proto.InternalMessageInfo

func (m *ServerResponse_Statistic) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServerResponse_Statistic) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PingCommand struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingCommand) Reset()         { *m = PingCommand{} }
func (m *PingCommand) String() string { return proto.CompactTextString(m) }
func (*PingCommand) ProtoMessage()    {}
func (*PingCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc56ba28a6aaff3d, []int{4}
}

func (m *PingCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingCommand.Unmarshal(m, b)
}
func (m *PingCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingCommand.Marshal(b, m, deterministic)
}
func (m *PingCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingCommand.Merge(m, src)
}
func (m *PingCommand) XXX_Size() int {
	return xxx_messageInfo_PingCommand.Size(m)
}
func (m *PingCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_PingCommand.DiscardUnknown(m)
}

var xxx_messageInfo_PingCommand proto.InternalMessageInfo

func (m *PingCommand) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Identifier)(nil), "api.Identifier")
	proto.RegisterType((*Point)(nil), "api.Point")
	proto.RegisterType((*ServerCommand)(nil), "api.ServerCommand")
	proto.RegisterType((*ServerResponse)(nil), "api.ServerResponse")
	proto.RegisterType((*ServerResponse_Statistic)(nil), "api.ServerResponse.Statistic")
	proto.RegisterType((*PingCommand)(nil), "api.PingCommand")
}

func init() { proto.RegisterFile("point_service.proto", fileDescriptor_bc56ba28a6aaff3d) }

var fileDescriptor_bc56ba28a6aaff3d = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xb1, 0x6e, 0xdb, 0x30,
	0x10, 0x35, 0x63, 0x3b, 0x8e, 0xce, 0x68, 0x12, 0x30, 0x1d, 0x08, 0xa1, 0x2d, 0x04, 0x0e, 0xad,
	0x50, 0x14, 0x1e, 0x52, 0x74, 0xeb, 0xd4, 0x4c, 0x06, 0x3a, 0x18, 0x4a, 0xf6, 0x82, 0x91, 0xae,
	0x06, 0x01, 0x9b, 0x14, 0xc8, 0xb3, 0x80, 0x7c, 0x4c, 0xb7, 0x8e, 0xfd, 0xc8, 0x42, 0xa4, 0x64,
	0xa9, 0x49, 0xe1, 0x4d, 0xef, 0xdd, 0xdd, 0x7b, 0x8f, 0x3c, 0x0a, 0x6e, 0x6a, 0xab, 0x0d, 0xfd,
	0xf0, 0xe8, 0x1a, 0x5d, 0xe2, 0xaa, 0x76, 0x96, 0x2c, 0x9f, 0xaa, 0x5a, 0xcb, 0x6f, 0x00, 0xeb,
	0x0a, 0x0d, 0xe9, 0x9f, 0x1a, 0x1d, 0x17, 0xb0, 0x68, 0xd0, 0x79, 0x6d, 0x8d, 0x60, 0x19, 0xcb,
	0x93, 0xa2, 0x87, 0x3c, 0x85, 0x8b, 0x72, 0xa7, 0xd1, 0xd0, 0xba, 0x12, 0x67, 0xa1, 0x74, 0xc4,
	0xf2, 0xd7, 0x19, 0xcc, 0x37, 0xad, 0xc1, 0x89, 0xf9, 0x0c, 0x96, 0x7b, 0xf4, 0x5e, 0x6d, 0xf1,
	0xe1, 0xa9, 0xc6, 0x4e, 0x62, 0x4c, 0xb5, 0xb3, 0x06, 0x29, 0x54, 0xa7, 0x71, 0xb6, 0x83, 0xad,
	0x77, 0x85, 0x6d, 0xf0, 0x75, 0x25, 0x66, 0xd1, 0xbb, 0xc7, 0xfc, 0x3d, 0x5c, 0x3e, 0x2a, 0x22,
	0x74, 0x4f, 0x1b, 0x74, 0x25, 0x1a, 0x12, 0xf3, 0x8c, 0xe5, 0x8b, 0xe2, 0x19, 0xdb, 0xfa, 0x3b,
	0x2c, 0x51, 0x37, 0xf8, 0xa0, 0xf7, 0x28, 0xce, 0x33, 0x96, 0x4f, 0x8b, 0x31, 0xc5, 0xdf, 0x01,
	0x44, 0xd5, 0xd0, 0xb0, 0x08, 0x0d, 0x23, 0xa6, 0x4d, 0xb1, 0x53, 0xa4, 0xe9, 0x50, 0xa1, 0xb8,
	0xc8, 0x58, 0xce, 0x8a, 0x23, 0xe6, 0x6f, 0x20, 0xd9, 0x59, 0xb3, 0x8d, 0xc5, 0x24, 0x14, 0x07,
	0x42, 0xde, 0xc1, 0xab, 0x7b, 0x74, 0x0d, 0xba, 0x3b, 0xbb, 0xdf, 0x2b, 0x53, 0x9d, 0xb8, 0x26,
	0x01, 0x8b, 0x32, 0x36, 0x75, 0x57, 0xd4, 0x43, 0xf9, 0x87, 0xc1, 0x65, 0x54, 0x29, 0xd0, 0xd7,
	0xd6, 0x78, 0x3c, 0x21, 0xb3, 0x86, 0xeb, 0xd8, 0x7b, 0x4f, 0x8a, 0xb4, 0x27, 0x5d, 0x7a, 0x31,
	0xcb, 0xa6, 0xf9, 0xf2, 0xf6, 0xed, 0x4a, 0xd5, 0x7a, 0xf5, 0xaf, 0xd0, 0xea, 0xd8, 0x55, 0xbc,
	0x18, 0x4b, 0xbf, 0x40, 0x72, 0x44, 0x9c, 0xc3, 0x8c, 0x86, 0xf5, 0x85, 0x6f, 0xfe, 0x1a, 0xe6,
	0x8d, 0xda, 0x1d, 0xfa, 0xad, 0x45, 0x20, 0x3f, 0xc0, 0x72, 0xa3, 0xcd, 0x76, 0x74, 0xe2, 0x6e,
	0xd7, 0x7d, 0xd4, 0x0e, 0xde, 0xfe, 0x66, 0x00, 0xce, 0x1e, 0x08, 0xe3, 0x0b, 0xfa, 0x08, 0xc9,
	0x77, 0xe5, 0x29, 0x82, 0xab, 0x10, 0x76, 0x78, 0x9f, 0x29, 0x04, 0x22, 0x14, 0xe5, 0x84, 0x7f,
	0x85, 0xab, 0x67, 0x71, 0x39, 0x1f, 0x1d, 0xaf, 0xf3, 0x4e, 0x6f, 0xfe, 0x73, 0x64, 0x39, 0xe1,
	0x9f, 0x60, 0xd6, 0x26, 0xe4, 0xd7, 0x51, 0x73, 0x08, 0x9b, 0xbe, 0x60, 0xe4, 0xe4, 0xf1, 0x3c,
	0xfc, 0x33, 0x9f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x59, 0xa8, 0x17, 0x14, 0x4a, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoutePointClient is the client API for RoutePoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoutePointClient interface {
	LastPoint(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Point, error)
	ServerStatistic(ctx context.Context, in *ServerCommand, opts ...grpc.CallOption) (*ServerResponse, error)
	Ping(ctx context.Context, in *PingCommand, opts ...grpc.CallOption) (*PingCommand, error)
}

type routePointClient struct {
	cc *grpc.ClientConn
}

func NewRoutePointClient(cc *grpc.ClientConn) RoutePointClient {
	return &routePointClient{cc}
}

func (c *routePointClient) LastPoint(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Point, error) {
	out := new(Point)
	err := c.cc.Invoke(ctx, "/api.routePoint/LastPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routePointClient) ServerStatistic(ctx context.Context, in *ServerCommand, opts ...grpc.CallOption) (*ServerResponse, error) {
	out := new(ServerResponse)
	err := c.cc.Invoke(ctx, "/api.routePoint/ServerStatistic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routePointClient) Ping(ctx context.Context, in *PingCommand, opts ...grpc.CallOption) (*PingCommand, error) {
	out := new(PingCommand)
	err := c.cc.Invoke(ctx, "/api.routePoint/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutePointServer is the server API for RoutePoint service.
type RoutePointServer interface {
	LastPoint(context.Context, *Identifier) (*Point, error)
	ServerStatistic(context.Context, *ServerCommand) (*ServerResponse, error)
	Ping(context.Context, *PingCommand) (*PingCommand, error)
}

func RegisterRoutePointServer(s *grpc.Server, srv RoutePointServer) {
	s.RegisterService(&_RoutePoint_serviceDesc, srv)
}

func _RoutePoint_LastPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutePointServer).LastPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.routePoint/LastPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutePointServer).LastPoint(ctx, req.(*Identifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutePoint_ServerStatistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutePointServer).ServerStatistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.routePoint/ServerStatistic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutePointServer).ServerStatistic(ctx, req.(*ServerCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutePoint_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutePointServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.routePoint/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutePointServer).Ping(ctx, req.(*PingCommand))
	}
	return interceptor(ctx, in, info, handler)
}

var _RoutePoint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.routePoint",
	HandlerType: (*RoutePointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LastPoint",
			Handler:    _RoutePoint_LastPoint_Handler,
		},
		{
			MethodName: "ServerStatistic",
			Handler:    _RoutePoint_ServerStatistic_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _RoutePoint_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "point_service.proto",
}
